### ISSUE TITLE
turn on clearMocks in jest conf

### ISSUE THREAD

**Issue by rluvaton** [practicajs/practica#32]
I think we should turn on `clearMocks` config in jest as otherwise, you can forget to clean mocks and it will affect your next tests

WDYT?

**Comment by goldbergyoni** [comment]
I suggest that we should not use Jest mocks at all.

Why? There are many discussions around whether Jest is a legit test runner. The arguments criticize its non-standard way of doing things and 'magical' approach. Among all the things, its mocking part is the worst - Too many complicated things are happening there. Due to this complexity, it is also not supporting ESM yet.

Consequently, I suggest going with Sinon as our mocking library or compare the alternatives.

WDYT? @rluvaton

**Comment by rluvaton** [comment]
So you have some reference to those arguments?

If we decide to go with that approach with should add some eslint rules which will warn when using jest mocks

**Comment by goldbergyoni** [comment]
@rluvaton  Jest itself stated in its ESM support doc that mocks are not supported. By design, it switches files location which IMO is not a straightforward engineering technique. Why don't use other test doubles library?

**Comment by rluvaton** [comment]
I understand, thank you!
